services:
  - type: web
    name: udemy-scraper-api
    env: docker
    plan: free # Changed to Free Tier (512MB RAM)
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "10000"
      - key: MONGO_URI
        sync: false
